# This is a basic workflow to help you get started with Actions

name: GitHub Pipeline Migrations

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
      username:
        required: false
        type: string
      password:
        required: false
        type: string
      locations:
        required: false
        type: string
        default: filesystem:./migrations
      initSql:
        required: false
        type: string
jobs:
  # This workflow contains a single job called "build"
  build-migrations:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Executions migrations
        uses: ./
        with:
          url: ${{ inputs.url }}
          user: ${{ inputs.username }}
          password: ${{ inputs.password }}
          locations: ${{ inputs.locations }}