nv.name: Exemplo de Workflow

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  exemplo:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar variáveis
        run: echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV

      - name: Exibir nome do repositório
        env:
          NOME_REPO: ${{ github.event.repository.name }}
          GITHUB_REPO_NAME: ${{env.NOME_REPO}}
        run: echo ${{ env.NOME_REPO }}
